---
apiVersion: v1
kind: ReplicationController
metadata:
  name: javawebapp
spec:
  replicas: 3
  selector:
     app: javawebapp
  template:
    metadata:
      name: javawebappod 
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javawebapcontainer
        image: ashokit/javawebapp
        ports:
        - containerPort: 8080
